//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace ornekproje
{
    using System;
    using System.Data.Entity;
    using System.Data.Entity.Infrastructure;
    
    public partial class Db_projeEntities0 : DbContext
    {
        public Db_projeEntities0()
            : base("name=Db_projeEntities0")
        {
        }
    
        protected override void OnModelCreating(DbModelBuilder modelBuilder)
        {
            throw new UnintentionalCodeFirstException();
        }
    
        public virtual DbSet<tblkullanici> tblkullanici { get; set; }
        public virtual DbSet<tblmusteri> tblmusteri { get; set; }
        public virtual DbSet<tblsatis> tblsatis { get; set; }
        public virtual DbSet<tblurun> tblurun { get; set; }
        public virtual DbSet<tblkategori> tblkategori { get; set; }
    }
}
