//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace ornekproje
{
    using System;
    using System.Collections.Generic;
    
    public partial class tblkullanici
    {
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2214:DoNotCallOverridableMethodsInConstructors")]
        public tblkullanici()
        {
            this.tblmusteri = new HashSet<tblmusteri>();
            this.tblsatis = new HashSet<tblsatis>();
            this.tblurun = new HashSet<tblurun>();
            this.tblkategori = new HashSet<tblkategori>();
        }
    
        public int kullanici_id { get; set; }
        public string kullanici_ad { get; set; }
        public string kullanici_sifre { get; set; }
        public string kullanıci_isim { get; set; }
        public string kullanici_soyad { get; set; }
        public string kullanici_adres { get; set; }
    
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<tblmusteri> tblmusteri { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<tblsatis> tblsatis { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<tblurun> tblurun { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<tblkategori> tblkategori { get; set; }
    }
}
