//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace ornekproje
{
    using System;
    using System.Collections.Generic;
    
    public partial class tblsatis
    {
        public int satis_id { get; set; }
        public Nullable<int> urun_id { get; set; }
        public Nullable<int> musteri_id { get; set; }
        public Nullable<int> kullanici_id { get; set; }
    
        public virtual tblkullanici tblkullanici { get; set; }
        public virtual tblmusteri tblmusteri { get; set; }
        public virtual tblurun tblurun { get; set; }
    }
}
